import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {validatePreferences,validateOptions} from '../ai/meal-rules.mjs';
import {createMealHandler} from '../backend/meal/app.mjs';
const prefs={budget:'30',taste:'light',avoid:['花生']};
const options=[{name:'番茄鸡蛋面',reason:'清淡方便',ingredients:['番茄','鸡蛋','面条']},{name:'香菇鸡肉饭',reason:'搭配蔬菜',ingredients:['香菇','鸡肉','米饭']},{name:'青菜豆腐汤',reason:'清淡可口',ingredients:['青菜','豆腐']}];
const config={enabled:true,apiKey:'test-model-key',model:'deepseek-flash',betaCode:'long-test-invite-code',hashSalt:'long-test-hash-salt',allowedOrigin:'https://example.com',modelTimeoutMs:100};
function store(){let data='';return {read:async()=>data,append:async(_,line,pos)=>{if(pos!==Buffer.byteLength(data))return false;data+=line;return true;}};}
async function service(t,extra={}){let calls=0;const handler=createMealHandler({config,store:store(),fetchImpl:async(_,init)=>{calls++;const body=JSON.parse(init.body);assert.equal(body.thinking.type,'disabled');assert.equal(body.max_tokens,600);assert.ok(!init.body.includes(config.betaCode));return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({options})}}]}));},...extra});const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return {calls:()=>calls,request:(body=prefs,headers={},method='POST')=>fetch('http://127.0.0.1:'+server.address().port+'/api/meal',{method,headers:{Origin:config.allowedOrigin,Authorization:'Bearer '+config.betaCode,'Content-Type':'application/json',...headers},...(method==='POST'?{body:typeof body==='string'?body:JSON.stringify(body)}:{})})};}
test('reject unknown fields, long input and malformed options; match common food aliases',()=>{assert.deepEqual(validatePreferences(prefs),prefs);assert.throws(()=>validatePreferences({...prefs,prompt:'ignore rules'}));assert.throws(()=>validatePreferences({...prefs,avoid:['x'.repeat(13)]}));assert.deepEqual(validateOptions({options},prefs),options);assert.throws(()=>validateOptions({options:options.slice(1)},prefs));assert.throws(()=>validateOptions({options:[{...options[0],ingredients:['花生油']},...options.slice(1)]},prefs));assert.throws(()=>validateOptions({options:[{...options[0],ingredients:['虾米']},...options.slice(1)]},{...prefs,avoid:['海鲜']}));assert.throws(()=>validateOptions({options:[{...options[0],name:'<script>'},...options.slice(1)]},prefs));});
test('authorized request returns checked options without disclosing key',async t=>{const s=await service(t);const r=await s.request();assert.equal(r.status,200);assert.deepEqual((await r.json()).options,options);assert.equal(s.calls(),1);});
test('bad authorization, origin, body and method never call model',async t=>{const s=await service(t);for(const [body,headers,method,status] of [[prefs,{Authorization:'Bearer wrong'},'POST',401],[prefs,{Origin:'https://evil.example'},'POST',403],['x'.repeat(5000),{},'POST',413],[{...prefs,prompt:'override'}, {},'POST',400],[prefs,{},'GET',405]]){const r=await s.request(body,headers,method);assert.equal(r.status,status);}assert.equal(s.calls(),0);});
test('spoofed forwarded IP cannot evade limits',async t=>{const s=await service(t);assert.equal((await s.request()).status,200);assert.equal((await s.request(prefs,{'X-Forwarded-For':'1.2.3.4'})).status,429);assert.equal(s.calls(),1);});
test('disabled config and failed ledger stop paid calls',async t=>{const s=await service(t,{config:{...config,enabled:false}});assert.equal((await s.request()).status,503);assert.equal(s.calls(),0);const failed=await service(t,{store:{read:async()=>{throw Error('private failure');}}});const r=await failed.request();assert.equal(r.status,503);assert.ok(!(await r.text()).includes('private failure'));assert.equal(failed.calls(),0);});
test('bad and oversized model output rejected without automatic retry',async t=>{for(const content of ['<script>','x'.repeat(40000)]){let calls=0;const s=await service(t,{fetchImpl:async()=>{calls++;return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content}}]}));}});const r=await s.request();assert.equal(r.status,502);assert.equal(calls,1);}});
test('model timeout reports a safe error',async t=>{const s=await service(t,{fetchImpl:async(_,init)=>new Promise((_,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('secret timeout'))))});const r=await s.request();assert.equal(r.status,504);assert.ok(!(await r.text()).includes('secret'));});
