const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(process.env.MEAL_ROOT||'.');
const server=http.createServer((req,res)=>{const name=path.join(root,new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html'));if(!name.startsWith(root+path.sep)){res.statusCode=403;return res.end();}fs.readFile(name,(err,data)=>{if(err){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.jpg':'image/jpeg'})[path.extname(name)]||'text/plain');res.end(data);});});
const options=[{name:'番茄鸡蛋面',reason:'清淡方便',ingredients:['番茄','鸡蛋','面条']},{name:'香菇鸡肉饭',reason:'搭配蔬菜',ingredients:['香菇','鸡肉','米饭']},{name:'青菜豆腐汤',reason:'清淡可口',ingredients:['青菜','豆腐']}];
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{
const disabled=await b.newPage();await disabled.route('**/ai/config.mjs*',r=>r.fulfill({contentType:'text/javascript',body:"export const mealConfig={endpoint:''};"}));await disabled.route('https://**/*',r=>r.abort());await disabled.goto(base);assert.equal(await disabled.locator('#meal-open').isVisible(),false,'unconfigured entry must stay hidden');await disabled.close();
for(const [width,height] of [[320,568],[393,720],[430,800],[1280,900]]){
 const p=await b.newPage({viewport:{width,height},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.abort());
 await p.route('**/ai/config.mjs*',r=>r.fulfill({contentType:'text/javascript',body:"export const mealConfig={endpoint:'https://meal.example/api/meal'};"}));let mode='success',calls=0;
 await p.route('https://meal.example/api/meal',async r=>{calls++;const req=r.request();assert.equal(req.headers().authorization,'Bearer test-invite-code-123');assert.deepEqual(req.postDataJSON(),{budget:'30',taste:'light',avoid:[]});if(mode==='offline')return r.abort();if(mode==='rate')return r.fulfill({status:429,contentType:'application/json',body:JSON.stringify({error:'今天的试用次数已用完，明天再来。'})});if(mode==='unsafe')return r.fulfill({contentType:'application/json',body:JSON.stringify({options:[{...options[0],name:'<script>'},...options.slice(1)]})});return r.fulfill({contentType:'application/json',body:JSON.stringify({options})});});
 await p.goto(base);await p.waitForSelector('#meal-open:visible');const original=await p.locator('#wheel').getAttribute('aria-label');await p.click('#meal-open');await p.selectOption('#meal-taste','light');await p.fill('#meal-code','test-invite-code-123');await p.click('#meal-submit');await p.waitForSelector('#meal-results li');assert.equal(await p.locator('#meal-results li').count(),3);assert.equal(await p.locator('#wheel').getAttribute('aria-label'),original,'results must not change menu');assert.equal(await p.evaluate(()=>localStorage.getItem('meal-code')),null);
 if(width===393){fs.mkdirSync(path.join(root,'artifacts'),{recursive:true});await p.locator('#meal-dialog').screenshot({path:path.join(root,'artifacts/meal-preview.png')});}
 const dialog=await p.locator('#meal-dialog').evaluate(e=>{const r=e.getBoundingClientRect();return {width:r.width,bottom:r.bottom};});assert.ok(dialog.width<=width&&dialog.bottom<=height,'dialog fits screen');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.click('#meal-apply');await p.waitForSelector('#meal-dialog:not([open])',{state:'attached'});assert.match(await p.locator('#wheel').getAttribute('aria-label'),/番茄鸡蛋面/);assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('personal-food-wheel-v1'))),options.map(x=>x.name));
 await p.click('#meal-open');await p.fill('#meal-code','test-invite-code-123');mode='rate';await p.click('#meal-submit');await p.waitForFunction(()=>document.querySelector('#meal-status').textContent.includes('次数已用完'));assert.equal(await p.locator('#meal-apply').isVisible(),false);mode='unsafe';await p.click('#meal-submit');await p.waitForFunction(()=>document.querySelector('#meal-status').textContent.includes('格式'));assert.equal(await p.locator('#meal-results script').count(),0);mode='offline';await p.click('#meal-submit');await p.waitForFunction(()=>document.querySelector('#meal-status').textContent.includes('连接'));mode='success';await p.click('#meal-submit');await p.waitForSelector('#meal-results li');let asked=false;p.once('dialog',d=>{asked=true;d.dismiss();});await p.click('#meal-apply');assert.equal(asked,true,'existing custom menu must require confirmation');assert.equal(await p.locator('#meal-dialog').evaluate(e=>e.open),true);await p.click('#meal-close');assert.equal(await p.locator('#meal-code').inputValue(),'');await p.click('#coffee');assert.equal(await p.locator('#meal-open').isVisible(),false);assert.deepEqual(errors,[]);assert.ok(calls>=4);await p.close();console.log(`PASS meal ${width}×${height}: result, apply, rate limit, offline, unsafe output, privacy and custom-menu confirmation`);
}
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
